# Generated by Django 5.1.1 on 2024-10-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controlroom", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryentry",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
