# Generated by Django 5.1.1 on 2024-10-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("controlroom", "0003_alter_transaction_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="user",
        ),
        migrations.DeleteModel(
            name="DiaryEntry",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
