# Generated by Django 5.1.1 on 2024-10-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("duration", models.IntegerField()),
                ("file_size_gb", models.FloatField()),
                ("video_resolution", models.CharField(max_length=50)),
                ("dimensions", models.CharField(max_length=50)),
                ("video_codec", models.CharField(max_length=50)),
                ("audio_streams", models.JSONField()),
                ("plex_rating_key", models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
