# Generated by Django 5.1.1 on 2024-10-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TVShow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plex_rating_key", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("seasons", models.IntegerField(default=0)),
                ("episodes", models.IntegerField(default=0)),
                ("file_size_gb", models.FloatField(default=0)),
                ("season_details", models.JSONField(default=list)),
            ],
        ),
    ]
